name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3-venv openjdk-17-jdk unzip
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Install Android SDK & AIDL
        run: |
          mkdir -p $GITHUB_WORKSPACE/.android
          export ANDROID_HOME=$GITHUB_WORKSPACE/.android
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529

          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

      - name: Install Python dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          source env/bin/activate
          buildozer android clean
          buildozer android debug
        env:
          ANDROID_HOME: ${{ github.workspace }}/.android
          ANDROID_NDK_HOME: ${{ github.workspace }}/.android/ndk/21.4.7075529

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GachaSimulator.apk
          path: bin/*.apk
